#!/usr/bin/env python3
"""Emit reviewer/_stanzas.py from entrypoint.sh's stanza assignments.

Run once, commit the output, delete nothing: this script is the provenance of
those four strings, and the fixture tests in tests/test_prompts.py are what
prove the extraction was faithful.
"""
import re
import sys

SRC = "entrypoint.sh"
WANT = {
    "_test_stanza": "TEST_STANZA",
    "_gh_stanza": "GH_STANZA",
    "_plan_stanza": "PLAN_STANZA",
}

out = {}
with open(SRC, encoding="utf-8") as fh:
    for line in fh:
        m = re.match(r'^(_\w+)="(.*)"$', line.rstrip("\n"))
        if m and m.group(1) in WANT:
            # Undo the shell's escaping inside a double-quoted string. Only
            # these three sequences appear; anything else would be a new escape
            # nobody vetted, so fail loudly rather than guess.
            body = m.group(2)
            if re.search(r'\\[^`$\\]', body):
                sys.exit(f"unexpected escape in {m.group(1)}; extend this script")
            body = body.replace("\\`", "`").replace("\\$", "$").replace("\\\\", "\\")
            out[WANT[m.group(1)]] = body

# The Linear stanza is the printf payload inside linear_stanza(), leading space
# included, so it is matched separately.
with open(SRC, encoding="utf-8") as fh:
    for line in fh:
        m = re.match(r"^\s*printf '%s' \"( If the PR title.*)\"$", line.rstrip("\n"))
        if m:
            body = m.group(1).replace("\\`", "`").replace("\\$", "$").replace("\\\\", "\\")
            out["LINEAR_STANZA"] = body

missing = {"TEST_STANZA", "GH_STANZA", "PLAN_STANZA", "LINEAR_STANZA"} - set(out)
if missing:
    sys.exit(f"did not find: {sorted(missing)}")

with open("reviewer/_stanzas.py", "w", encoding="utf-8") as fh:
    fh.write('"""Generated by tools/extract-stanzas.py from entrypoint.sh.\n\n')
    fh.write("Do not hand-edit. See prompts.py for what each stanza is for, and\n")
    fh.write('tests/test_prompts.py for the fixtures that pin them.\n"""\n\n')
    for name in ("GH_STANZA", "TEST_STANZA", "PLAN_STANZA", "LINEAR_STANZA"):
        fh.write(f"{name} = {out[name]!r}\n\n")
print("wrote reviewer/_stanzas.py")
